<div class="pull-right span3">
<div class="panel panel-default">
	<div class="panel-heading">
		<h3 class="panel-title">News</h3>
	</div>
	<div class="panel-body">
		<div class="media">
			<a class="pull-left" href="#">
				<img class="media-object" style="height: 70px; width: 70px;" src="http://inyaproduction.de/media/images/inya.png" alt="InyaLogo">
			</a>
			<div class="media-body">
				<h4 class="media-heading">InyaProduction</h4>
				InyaProduction's neue Website
			</div>
		</div>
	</div>
</div> 
</div>
