<div class="navbar navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">
			<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</a>
			<a class="brand" href="#"><?php echo Core::config()->getConfig('title'); ?></a>
			<div class="nav-collapse collapse">
				<ul class="nav">
				<?php echo $navi->getNaviLinks(); ?>
				</ul>
			</div>
		</div>
	</div>
</div>


<form action="api?api=1&api_key=login" method="post">
<div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
		<h3 id="myModalLabel">Login</h3>
	</div>
	<div class="modal-body">
	<?php if(!Core::getInstance()->getLib('User')->isLoggedIn() == true): ?>
		<center>
				<div class="input-prepend">
					<span class="add-on"><span class="glyphicon glyphicon-user"></span></span>
					<input id="" name="username" type="text" class="form-control" placeholder="Nutzername">
				</div>
				<br />
				<div class="input-prepend">
					<span class="add-on"><span class="glyphicon glyphicon-pencil"></span></span>
					<input id="" name="password" type="password" class="form-control" placeholder="Passwort">
				</div>
		</center>
	<?php else: ?>
		<p>Du bist bereits eingeloggt!</p>
	<?php endif; ?>
	</div>
	<div class="modal-footer">
		<button class="btn" data-dismiss="modal" aria-hidden="true">Schlie&szlig;en</button>
		<button class="btn btn-primary" type="submit">Login</button>
	</div>
</div>
</form>
<div class="clearfix"></div>
