<div class="panel panel-default">
	<div class="panel-heading">
		<h3 class="panel-title">Registration</h3>
	</div>
	<div class="panel-body">
	<div id="message"></div>
	<table class="table">
		<tr>
			<td>Nutzername:</td>
			<td>
				<div class="input-prepend">
					<span class="add-on"><span class="glyphicon glyphicon-user"></span></span>
					<input id="userTool" href="#" data-toggle="tooltip" title="3-16 Zeichen" name="username" type="text" class="form-control" placeholder="Nutzername">
				</div>
			</td>
			<td><span class="glyphicon" id="userCheck"></span></td>
		</tr>
		<tr>
			<td>Passwort:</td>
			<td>
				<div class="input-prepend">
					<span class="add-on"><span class="glyphicon glyphicon-pencil"></span></span>
					<input id="pwTool" href="#" data-toggle="tooltip" title="Kennwort eingeben (6-20 Zeichen)" name="password" type="password" class="form-control" placeholder="Passwort">
				</div>
			</td>
			<td><span class="glyphicon" id="pwCheck"></span></td>
		</tr>
		<tr>
			<td>Passwort wiederholen:</td>
			<td>
				<div class="input-prepend">
					<span class="add-on"><span class="glyphicon glyphicon-pencil"></span></span>
					<input id="pw2Tool" href="#" data-toggle="tooltip" title="Kennwort wiederholen" name="password" type="password" class="form-control" placeholder="Passwort">
				</div>
			</td>
			<td><span class="glyphicon" id="pw2Check"></span></td>
		</tr>
		<tr>
			<td>Name:</td>
			<td>
				<div class="input-prepend">
					<span class="add-on"><span class="glyphicon glyphicon-pencil"></span></span>
					<input id="nameTool" href="#" data-toggle="tooltip" title="Ihr Vor- und Zuname" name="name" type="text" class="form-control" placeholder="Name">
				</div>
			</td>
			<td><span class="glyphicon" id="nameCheck"></span></td>
		</tr>
		<tr>
			<td>Email:</td>
			<td>
				<div class="input-prepend">
					<span class="add-on"><span class="glyphicon glyphicon-envelope"></span></span>
					<input id="emailTool" href="#" data-toggle="tooltip" title="Ihre Emailadresse" name="email" type="text" class="form-control" placeholder="Email">
				</div>
			</td>
			<td><span class="glyphicon" id="emailCheck"></span></td>
		</tr>
	</table>
		<button class="btn btn-primary" id="sendRegister">Absenden</button>
	</div>
</div> 
 
